package de.hahn.blog.treetable.model.views;

import de.hahn.blog.treetable.model.entities.DepartmentsImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 22 21:53:48 CEST 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentsViewRowImpl extends ViewRowImpl {

    public static final int ENTITY_DEPARTMENTS = 0;
    public static final int ENTITY_EMPLOYEES = 1;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        DepartmentId,
        DepartmentName,
        ManagerId,
        LocationId,
        MgrLastName,
        MgrEmployeeId,
        MgrFirstName,
        EmployeesView,
        ManagerView;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int DEPARTMENTID = AttributesEnum.DepartmentId.index();
    public static final int DEPARTMENTNAME = AttributesEnum.DepartmentName.index();
    public static final int MANAGERID = AttributesEnum.ManagerId.index();
    public static final int LOCATIONID = AttributesEnum.LocationId.index();
    public static final int MGRLASTNAME = AttributesEnum.MgrLastName.index();
    public static final int MGREMPLOYEEID = AttributesEnum.MgrEmployeeId.index();
    public static final int MGRFIRSTNAME = AttributesEnum.MgrFirstName.index();
    public static final int EMPLOYEESVIEW = AttributesEnum.EmployeesView.index();
    public static final int MANAGERVIEW = AttributesEnum.ManagerView.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentsViewRowImpl() {
    }

    /**
     * Gets Departments entity object.
     * @return the Departments
     */
    public DepartmentsImpl getDepartments() {
        return (DepartmentsImpl) getEntity(ENTITY_DEPARTMENTS);
    }

    /**
     * Gets Employees entity object.
     * @return the Employees
     */
    public EntityImpl getEmployees() {
        return (EntityImpl) getEntity(ENTITY_EMPLOYEES);
    }

    /**
     * Gets the attribute value for DEPARTMENT_ID using the alias name DepartmentId.
     * @return the DEPARTMENT_ID
     */
    public Integer getDepartmentId() {
        return (Integer) getAttributeInternal(DEPARTMENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPARTMENT_ID using the alias name DepartmentId.
     * @param value value to set the DEPARTMENT_ID
     */
    public void setDepartmentId(Integer value) {
        setAttributeInternal(DEPARTMENTID, value);
    }

    /**
     * Gets the attribute value for DEPARTMENT_NAME using the alias name DepartmentName.
     * @return the DEPARTMENT_NAME
     */
    public String getDepartmentName() {
        return (String) getAttributeInternal(DEPARTMENTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPARTMENT_NAME using the alias name DepartmentName.
     * @param value value to set the DEPARTMENT_NAME
     */
    public void setDepartmentName(String value) {
        setAttributeInternal(DEPARTMENTNAME, value);
    }

    /**
     * Gets the attribute value for MANAGER_ID using the alias name ManagerId.
     * @return the MANAGER_ID
     */
    public Integer getManagerId() {
        return (Integer) getAttributeInternal(MANAGERID);
    }

    /**
     * Sets <code>value</code> as attribute value for MANAGER_ID using the alias name ManagerId.
     * @param value value to set the MANAGER_ID
     */
    public void setManagerId(Integer value) {
        setAttributeInternal(MANAGERID, value);
    }

    /**
     * Gets the attribute value for LOCATION_ID using the alias name LocationId.
     * @return the LOCATION_ID
     */
    public Integer getLocationId() {
        return (Integer) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCATION_ID using the alias name LocationId.
     * @param value value to set the LOCATION_ID
     */
    public void setLocationId(Integer value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for LAST_NAME using the alias name MgrLastName.
     * @return the LAST_NAME
     */
    public String getMgrLastName() {
        return (String) getAttributeInternal(MGRLASTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_NAME using the alias name MgrLastName.
     * @param value value to set the LAST_NAME
     */
    public void setMgrLastName(String value) {
        setAttributeInternal(MGRLASTNAME, value);
    }

    /**
     * Gets the attribute value for EMPLOYEE_ID using the alias name MgrEmployeeId.
     * @return the EMPLOYEE_ID
     */
    public Integer getMgrEmployeeId() {
        return (Integer) getAttributeInternal(MGREMPLOYEEID);
    }

    /**
     * Sets <code>value</code> as attribute value for EMPLOYEE_ID using the alias name MgrEmployeeId.
     * @param value value to set the EMPLOYEE_ID
     */
    public void setMgrEmployeeId(Integer value) {
        setAttributeInternal(MGREMPLOYEEID, value);
    }

    /**
     * Gets the attribute value for FIRST_NAME using the alias name MgrFirstName.
     * @return the FIRST_NAME
     */
    public String getMgrFirstName() {
        return (String) getAttributeInternal(MGRFIRSTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for FIRST_NAME using the alias name MgrFirstName.
     * @param value value to set the FIRST_NAME
     */
    public void setMgrFirstName(String value) {
        setAttributeInternal(MGRFIRSTNAME, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link EmployeesView.
     */
    public RowIterator getEmployeesView() {
        return (RowIterator) getAttributeInternal(EMPLOYEESVIEW);
    }

    /**
     * Gets the associated <code>ViewRowImpl</code> using master-detail link ManagerView.
     */
    public ViewRowImpl getManagerView() {
        return (ViewRowImpl) getAttributeInternal(MANAGERVIEW);
    }

    /**
     * Sets the master-detail link ManagerView between this object and <code>value</code>.
     */
    public void setManagerView(ViewRowImpl value) {
        setAttributeInternal(MANAGERVIEW, value);
    }
}

